name: API CI

on:
  push:
    branches: [ master ]
    paths:
    - 'api/**'
    - '.github/workflows/**'

jobs:
  api-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.3
      with:
        node-version: 12

    - name: API Install Dependencies
      run: cd api && yarn install --frozen-lockfile

    - name: API Build
      run: cd api && yarn build

    - name: Rsync API files
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude .env --exclude node_modules
        path: api/
        remote_path: ${{ secrets.REMOTE_APP_PATH }}/api/
        remote_host: ${{ secrets.HOST }}
        remote_port: ${{ secrets.PORT }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.KEY }}

    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ${{ secrets.REMOTE_APP_PATH }}/api
          ${{ secrets.YARN_BIN_PATH }} install --frozen-lockfile
          sudo systemctl restart rower-stats-api.service
